//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace telaDeLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients_endereco
    {
        public int id_clients { get; set; }
        public int id_endereco { get; set; }
    
        public virtual clients_endereco clients_endereco1 { get; set; }
        public virtual clients_endereco clients_endereco2 { get; set; }
    }
}
